#ifndef SIMULATORDATAWIDGET_P_H
#define SIMULATORDATAWIDGET_P_H

#define V_BOX_LAYOUT_MARGIN    5
#define V_BOX_LAYOUT_SPACING   2

#define G_BOX_LAYOUT_MARGIN    10
#define G_BOX_LAYOUT_SPACING   6

#define BTN_BOX_LAYOUT_MARGIN  5
#define BTN_BOX_LAYOUT_SPACING 2

#endif // SIMULATORDATAWIDGET_P_H
